version: "3"

services:
  tf:
    image: dmccloskey/docker-pyopenms-vscode
    volumes:
      # 1
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_FastPeak/openMS_MRMworkflow/:/home/user/openMS_MRMworkflow/
      # - //C/Users/domccl/GitHub/smartPeak/py/:/home/user/code/
      # 2
      - //C/Users/dmccloskey/Documents/GitHub/TensorFlow_tutorials:/home/user/code/
    ports:
      - "3000:3000"
    command: python /home/user/code/debug_remote.py
    restart: always
    networks:
      - tf_network
    
networks:
  tf_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16